### ISSUE TITLE
Password-protected PDF files.

### ISSUE THREAD

**Issue by keevee09** [ropensci/rtika#4]
Is there an argument that can be passed to tika_text() to open a password-protected PDF document?

**Comment by soshsquatch** [comment]
Although tika_text() does not have that option, the following should work for a single pdf:

```
my_file = '/path' # path to your file
my_password = 'password_string'  # password string

text <- base::rawToChar(sys::exec_internal('java',
 c('-jar',tika_jar(), 
  '--text',
  paste0('--password=',my_password),
 my_file ))$stdout)

```
This calls Tika in the normal mode instead of 'batch mode'. In normal mode, you must process one file at a time. There are a few more options in the normal mode as of writing, although this should eventually change with the stabilization of the custom config files.

The other options for normal mode are viewed using:
```
sys::exec_wait('java',c('-jar',tika_jar(), '--help'))
```
